### ISSUE TITLE
Own expose server (docker-compose) not redirecting to local machine

### ISSUE THREAD

**Issue by waterdrop01** [beyondcode/expose#134]
Hello there! 

I stumbled upon expose when looking for custom subdomain with ngrok (which is now a premium/paying option).

I'm running the server in docker (using docker-compose). Here is the `docker-compose.yml`:
```
version: "3"

services:
  expose:
    image: beyondcodegmbh/expose-server:latest
    networks:
      - web
    ports:
      - 9191:9191
    environment:
      port: 9191
      domain: expose.mydomain.tld
      username: admin
      password: password
    restart: always
    volumes:
      - ./database/expose.db:/root/.expose
```
I allowed port 9191 on the same server doing `ufw allow 9191`.

Then I started my local application, that is also listening on port 9191 (could be another one).

Finally I ran client expose command: `expose share 127.0.0.1:9191 --subdomain=subdomain`

PROBLEM: When doing a curl POST request on `127.0.0.1:9191`, I can see it on my local application logs. But when doing the same curl POST request on `http://subdomain.expose.mydomain.tld:9191` -> NOTHING. The curl command is hanging indefinitely.

**Any help would be much appreciated!**

Note: The connection between local expose client and server is OK (can see the corresponding line in the server admin dashboard). But nothing in the client admin dashboard.

Note 2 : Here is my client `~/.expose.config.pjp`:
```
    /*
    |--------------------------------------------------------------------------
    | Host
    |--------------------------------------------------------------------------
    |
    | The expose server to connect to. By default, expose is using the free
    | sharedwithexpose.com server, offered by Beyond Code. You will need a free
    | Beyond Code account in order to authenticate with the server.
    | Feel free to host your own server and change this value.
    |
    */
    'host' => 'expose.mydomain.tld',

    /*
    |--------------------------------------------------------------------------
    | Port
    |--------------------------------------------------------------------------
    |
    | The port that expose will try to connect to. If you want to bypass
    | firewalls and have proper SSL encrypted tunnels, make sure to use
    | port 443 and use a reverse proxy for Expose.
    |
    | The free default server is already running on port 443.
    |
    */
    'port' => 9191,
```
