### ISSUE TITLE
Error `The "-c" option does not exist.` when running latest(1.4.1) docker image

### ISSUE THREAD

**Issue by cpxPratik** [beyondcode/expose#165]
With the change of entry point to "/src/expose", the image now runs with command `"/src/expose /bin/sh -c 'sed -i ...`.

But for some reason with this change, `-c` option is assumed to be from `expose` instead of `sh`. The container keeps restarting.

Contaienr log shows 

```
Error `The "-c" option does not exist.
```

Previously on 1.3.4 version, it would run as `"docker-php-entrypoint /bin/sh -c 'sed -i ...`

**Comment by MeestorX** [comment]
Same problem for me.

**Comment by PKeidel** [comment]
+1 Same error here

**Comment by matthieumota** [comment]
This is a conflict between ENTRYPOINT and CMD.
Docker run `/src/expose /bin/sh -c serve` this way, which is not at all correct and makes the CMD part unusable.
Also, it's necessary to create a custom sh script as entrypoint to run `/src/expose`.
I've made a PR. #174

**Comment by gclark18** [comment]
That PR does not resolve the issue for me when using docker compose.

**Comment by matthieumota** [comment]
PR is not merged so with latest image, you don't get that fix. You need to clone PR and build manually if you want to try.

**Comment by dbpolito** [comment]
While the PR is not merged and you want to run on latest image, change your `docker-compose.yml` to:

```yml
    image: beyondcodegmbh/expose-server:1.5.0 # or latest
    entrypoint: ["sh", "-c"]
    command: sed -i "s|username|${username}|g" ${exposeConfigPath} && sed -i "s|password|${password}|g" ${exposeConfigPath} && php expose serve ${domain} --port ${port} --validateAuthTokens
```
