### ISSUE TITLE
Need proper documentation for how to use in docker

### ISSUE THREAD

**Issue by ridislam** [beyondcode/expose#180]
My local project is running on docker, in the docker workspace, I tried to install the package globally as mentioned in the doc.
then I authenticated using my beyond code account license token as mentioned in the doc
<img width="741" alt="Screenshot 2021-01-18 at 12 50 54 PM" src="https://user-images.githubusercontent.com/7835820/104881623-d1326880-598b-11eb-97cb-1bf8a88c2835.png">

here is my docker-compose.yml content
```
version: '3.5'
services:
  nginx:
    container_name: foodex_nginx
    image: nginx:latest
    ports:
      - "8080:80"
      - "8180:443"
    volumes:
      - ./:/var/www/html
      - ./docker/conf/:/etc/nginx/conf.d/
      - ./docker/www_logs/nginx:/var/log/nginx
    links:
      - phpfpm
  phpfpm:
    ports:
      - "6001:6001"
    container_name: foodex_app
    build: docker/containers/php74-fpm
    command: bash -c "/etc/init.d/cron start && php-fpm -F"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
  mysql:
    container_name: foodex_mysql
    image: mariadb:latest
    volumes:
      - ./docker/conf/mysql:/etc/mysql/conf.d
      - ./docker/mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foodex
  phpmyadmin:
    container_name: foodex_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    ports:
      - '8079:80'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      PMA_HOST: mysql
  mailhog:
    container_name: foodex_mailhog
    image: mailhog/mailhog:latest
    ports:
      - 8025:8025
      - 1025:1025
```
When I try to browse the exposed link it shows 504 Gateway Time-out
<img width="1271" alt="Screenshot 2021-01-18 at 12 51 58 PM" src="https://user-images.githubusercontent.com/7835820/104881757-16569a80-598c-11eb-923d-4a27bd9c27e3.png">
Here is my site.conf 
```
server {
 listen 8080;
 server_name foodex.loc;
 return 301 https://$host$request_uri;
}

server {
    index index.php;
    server_name foodex.loc;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/html/public;
    client_max_body_size 300M;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass phpfpm:9000;
        fastcgi_index index.php;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300;
        fastcgi_buffers 8 16k;
        fastcgi_buffer_size 32k;
        fastcgi_connect_timeout 300;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
            #
            # Custom headers and headers various browsers *should* be OK with but aren't
            #
            add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization,X-CSRF-Token';
            #
            # Tell client that this pre-flight info is valid for 20 days
            #
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }


    }

}

```
