### ISSUE TITLE
Running expose server

### ISSUE THREAD

**Issue by gclark18** [beyondcode/expose#182]
I ran docker-compose.yml file from my local server, and tried to access:

`http://expose.192.168.0.2:8085`

But the connection times out

Here is the `docker-compose.yml` file:

```yml
version: "3.7"
services:
  expose:
    image: beyondcodegmbh/expose-server:1.3.4
    ports:
      - 8080:${PORT}
    environment:
      port: ${PORT}
      domain: ${DOMAIN}
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
    restart: always
    volumes:
      - ./database/expose.db:/root/.expose
```

I'm using version `1.3.4` as the any container passed this will not start.

Can anyone assist?
