### ISSUE TITLE
504 Gateway Time-out with Docker Container

### ISSUE THREAD

**Issue by dimitribocquet** [beyondcode/expose#315]
- Expose version: 2.2.0
- Docker version: 4.6.1
- Computer: OSX 11.6 (Mac Mini M1)

Hello !

I have an app running with Sail, and I want to run another container to share it with expose, and I got a 504 Gateway Time-out.
When I use expose on my computer (not inside a container) via composer, it works. I got this error only when I use Expose inside a container. I see the request etc, but I got no response.

I tried to share my app with a (trial) Pro Expose account and my self hosted Expose server on a VPS, neither of them works.

In CLI:

```bash
expose share http://localhost:8000 --server-host=example.xyz --server-port=3000 --subdomain=api
```

docker-compose:

```yml
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - minio
    # ...
    expose_app:
        image: beyondcodegmbh/expose-server:latest
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        links:
          - laravel.test
        networks:
            - sail
        command:
            share laravel.test --server-host=${EXPOSE_SERVER_HOST:-example.xyz} --server-port=${EXPOSE_SERVER_PORT:-3000} --subdomain=${EXPOSE_SUBDOMAIN:-laravel} --auth=${EXPOSE_TOKEN}
```
